### ISSUE TITLE
Error on failed test

### ISSUE THREAD

**Issue by bon** [tdrhq/slite#4]
Getting the following error

`error in process filter: if: No catch for tag: --cl-block-nil--, "(+ 1 1) evaluated to 2 which is not = to 3"`

Nothing is shown in the `*Test Results*` buffer

**Comment by tdrhq** [comment]
Which CL implementation is this?

**Comment by bon** [comment]
sbcl 2.2.4
emacs 29.0.50

**Comment by tdrhq** [comment]
Ah this is coming from elisp. Most likelys one of the deprecated uses of cl-return, let me see if I can fix this real quick

**Comment by tdrhq** [comment]
I pushed this patch: https://github.com/tdrhq/slite/commit/c1f25db0c23f2e79985fe0d1dbf20e06f0c0369f. I haven't tested this against Emacs 29 (I'm on emacs 28), but I *think* it should do the trick. Let me know if it works.

**Comment by bon** [comment]
The ridiculously fast turnaround is much appreciated!
Unfortunately no change on emacs 29.
I'll give it a try on emacs 28

**Comment by tdrhq** [comment]
I pushed another change https://github.com/tdrhq/slite/commit/ce25176c92b3c17f157e09fb4ce70b3f446d4152 to try.

Let me know if this new change works, if not, I'll install Emacs 29 and give it a go. I should be upgrading anyway.

**Comment by bon** [comment]
Yes! Just got back to this and the latest commit works. 
For some reason my config is no longer working on emacs28 so I can't confirm about that but with emacs29 it's working perfectly for passing and failing tests.

Again, thanks for your prompt turnaround on this issue. Slite is an excellent additon to the Slime experience!

**Comment by tdrhq** [comment]
Awesome! Thanks for testing it out!
