### ISSUE TITLE
Handling FOR-ALL-TEST-RESULT

### ISSUE THREAD

**Issue by ykonai** [tdrhq/slite#8]
Hi,

In FIVEAM, tests written with the FOR-ALL macro return a FOR-ALL-TEST-RESULT object, which (usually?) has the TEST-EXPRESSION slot unbound. This results in errors. 
An additional method is sufficient to fix this:
```
(defmethod slite/fiveam::test-expression :around ((result fiveam::for-all-test-result))
  "The test-expression slot in FOR-ALL-TEST-RESULT objects is usually unbound, so
return N/A instead.

Use :around as all fiveam::for-all-test-result subclasses also inherit
fiveam::test-result."
  "N/A")
```

**Comment by tdrhq** [comment]
This was fixed in https://github.com/tdrhq/slite/commit/4c6a14dde4b969b71c937bc10fedf0dd7d59fc76
