### ISSUE TITLE
Prototype of `slite--compilation-finished` is incompatible with SLIME v2.30

### ISSUE THREAD

**Issue by fehmud** [tdrhq/slite#9]
`slite--compilation-finished` has this prototype:

    (defun slite--compilation-finished (successp _notes _buffer _loadp)

But `slime-compilation-finished-hook` in SLIME v2.30 only passes a list of notes, so the prototype should be like like this:

    (defun slite--compilation-finished (_notes)

**Comment by tdrhq** [comment]
Can you test this commit: https://github.com/tdrhq/slite/commit/47d69f0bc427d11d55cd5db0954fd59f3dbf1931 ?

I've re-written it in a way that should work on both SLY and Slime, but only tested it on SLY. Let me know if it works for you on Slime.

Thanks!

**Comment by fehmud** [comment]
@tdrhq: yes, it works. Thank you.
